name: Create Release
on:
  pull_request:
    types: [closed]
jobs:
  create-release:
    uses: lowranceworks/common-workflows/.github/create-tag-and-release.yaml@main
    permissions:
      contents: write
      pull-requests: read
      issues: read
